import type { Metadata } from "next";
import "./globals.css";
import {
  diatypeRegular,
  diatypeMedium,
  diatypeMonoRegular,
  diatypeMonoMedium,
  diatypeCondensedMedium,
} from "@/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${diatypeRegular.variable} ${diatypeMedium.variable} ${diatypeMonoRegular.variable} ${diatypeMonoMedium.variable} ${diatypeCondensedMedium.variable}`}
    >
      <body className="font-tandem-regular antialiased relative">{children}</body>
    </html>
  );
}
